### ISSUE TITLE
Bad asymptotic complexity with many nested futures

### ISSUE THREAD

**Issue by DemiMarie** [rust-lang-nursery/futures-rs#1004] opened 2018-05-09 17:51 UTC
Looking through the source code, it appears that deeply nested futures can require quadratic time to resolve.  The culprit is the need to poll every nested future, rather than the event loop polling the innermost future directly.

**Comment by DemiMarie** [comment] 2018-05-09 18:43
This is ugly.  The only workaround I can think of is to move from a polling-based model to a callback-based one.  If we do not want to regress on performance by using `Rc<RefCell<Future>>` everywhere (yuck), I cannot think of any approaches that do not:

1. Require that all futures are pinned in memory once they begin to be polled, so that the task can maintain a reference to them.
2. Require that the `Future` trait be changed to something like:

    ```rust
    pub trait Future<T> where T: ?Sized {
        fn attach_cb(&mut Self, cb: FnOnce(T) -> ());
    }
    ```

    But that of course will not compile due to a missing lifetime, and creates an ugly circular reference that makes it very hard (if not impossible) to create a custom future in safe code.  Since the future cannot move, its lifetime must be that of its parent object, so it is safe for it to have a reference to its parent object.  But I see no way to prove that to the compiler.

**Comment by DemiMarie** [comment] 2018-05-09 19:42
The number of times `.and_then` is called.

**Comment by carllerche** [comment] 2018-05-09 19:48
I'm not sure how you work it out to being quadratic. Could you explain that more?

**Comment by withoutboats** [comment] 2018-05-09 20:37
You need to be a lot more specific about what the issue is here. We've experienced some examples of quadratic behavior because of large generic types created through combinators, but they've been resolved effectively through caching. This has to do with the specific way combinators are implemented (through generics) and has nothing to do with the poll based approach.

I'm going to close this. Feel free to open another issue with a more specific explanation of the problem before you start jumping into very radical solutions.

**Closed by withoutboats** 2018-05-09 20:37 UTC
