### ISSUE TITLE
Should JoinHandle be exported?

### ISSUE THREAD

**Issue by bluetech** [rust-lang-nursery/futures-rs#819] opened 2018-02-28 08:54 UTC
The `executor` crate exports `spawn_with_handle` and `SpawnWithHandle` but not `JoinHandle`. Should it be? (If not, then references to it should be removed from the documentation, currently they are broken links).

**Comment by aturon** [comment] 2018-03-19 22:35
Dupe of #850, closing.

**Closed by aturon** 2018-03-19 22:35 UTC
