### ISSUE TITLE
Difficulty translating existing benchmarking to using `CurrentThread`

### ISSUE THREAD

**Issue by alexcrichton** [rust-lang-nursery/futures-rs#698] opened 2018-01-09 01:43 UTC
In tokio-core there's some existing benchmarking code that looks like:

```rust
let reactor = ...;
let handle = reactor.handle();

handle.spawn(/* some TCP listener task */);

bh.iter(|| {
    core.run(some_local_task);
});
```

The idea here is that there's a daemon/background task which is being used to process some data (like accepting TCP sockets). This persistent daemon task, thougho, is paired up with synchronously running futures in lockstep (specifically benchmarking the timing of each iteration in this case).

Unfortunately though this represents a pattern which isn't translateable to `CurrentThread`. Notably you can't build a "context" which is persistently used amongst several blocking scopes. For example every time a `CurrentThread` scope exits and reenters there's no data that's preserved across the boundaries (like the necessary daemon task in this case).

Is this something we want to accomodate? Say "don't do this"? I'm not sure how often this would come up in other contexts, although I suspect it will become quite relevant for client-side integration of futures which blocks much more maybe?

**Comment by carllerche** [comment] 2018-01-10 04:24
Setting up something like this has been made more difficult by design. By spawning daemon tasks and then intermittently calling `core.run` while mixing in other potentially blocking logic is a hazard. When the core is not running, the daemon task cannot make progress.

One option today would be to spawn the listener task on a thread pool.

One reason I added `&mut Context` as an argument to provide the ability to re-add similar functionality at a later time. The `&mut Context` can have a `yield_to_executor(fut)` function that allows driving a single future to completion similar to the setup you have above.

I did not yet propose such a function as it carries the same hazards mentioned above.

**Comment by carllerche** [comment] 2018-01-29 23:00
I can add a `block_on(fut)` to `Context` if we like that idea.

I also don't have a great idea for a name, but `block_on` seems ok.

**Comment by aturon** [comment] 2018-01-31 04:14
@carllerche IMO, let's not add anything right now, and instead wait for feedback.

@alexcrichton, are you still planning to add unstable features? That can be another route for experimentation with new APIs like this.

**Comment by alexcrichton** [comment] 2018-01-31 06:08
@aturon I think it's fine for us to add that on an as-needed basis (although I'd like to originally populate it with `Sleep` if we plan on keeping it for the first release). 

For `block_on` though I'd personally like to see that in the first release rather than behind an unstable feature to start out with.

**Comment by aturon** [comment] 2018-02-12 21:16
Closing in favor of the [executor RFC](https://github.com/rust-lang-nursery/futures-rfcs/pull/3).

**Closed by aturon** 2018-02-12 21:16 UTC
Labels: tokio-reform
