### ISSUE TITLE
Executor Behavior for WebAssembly

### ISSUE THREAD

**Issue by CryZe** [rust-lang-nursery/futures-rs#738] opened 2018-02-08 16:08 UTC
We are implementing an Executor that can run in a WebAssembly environment for stdweb. Since WebAssembly, at least at the moment, is completely single threaded, we need to implement an Executor that works in such an environment. The idea is to just execute all the Tasks on submission / notification immediately at that point in time. So when a Task is submitted and not quite done yet, the execution just yields back out and on notification, the execution continues. So it's actually very simple. However there's the edge case of a future being resubmitted while it is being executed. The documentation states that we need to poll the future again after its current execution:
```
If the task is currently polling its future when notify is called, it must poll the future again afterwards, ensuring that all relevant events are eventually observed by the future.
```
We implemented that, but now there's the potential situation that when a future calls notify() without actually being able to make progress, it potentially infinitely gets requeued, executed again, requeued, executed again, completely locking up that single thread.

Now the question is whether the executor needs to be able to handle such a case where a future calls notify() without actually being able to make any new progress, or if that's against the contract of the Task API.

If it is indeed valid behavior, then we need to defer the reexecution by using setTimeout / requestAnimationFrame / ... so the runtime can make progress in the meantime, allowing the future to eventually resolve itself. This however forces an additional import onto the wasm module, which would be quite unfortunate. Additionally it also seems to slow down the implementation.

The Pull Request for the futures integration for stdweb is here: https://github.com/koute/stdweb/pull/103

**Comment by Pauan** [comment] 2018-02-08 16:35
To add some more context, we are referring to [this sort of behavior](https://github.com/Pauan/stdweb/blob/d32d5d71ecc8e7b56bfc5a3ed7d032e83afc9e45/examples/promise/src/main.rs#L57-L75).

Also, [here is the source code for our Executor](https://github.com/Pauan/stdweb/blob/d32d5d71ecc8e7b56bfc5a3ed7d032e83afc9e45/src/webcore/promise_executor.rs).

If the `Executor` uses `setTimeout` to defer the execution of the Future, then the Future *can* make progress (because `setTimeout` yields control to the browser's event loop). If it doesn't use `setTimeout` then it will spin in an infinite loop and will completely dead-lock (preventing all progress).

Also, we only need to use `setTimeout` when a Future calls `task.notify()` within its implementation of `poll` (which seems to be rare), so I think the performance difference is minor either way.

**Comment by tailhook** [comment] 2018-02-08 23:16
As far as I understand, FuturesUnordered would behave the same. So yes, it's completely acceptable deadlock.

The idea is that current task shouldn't be used on the current task but kept somewhere else and triggered from there. For example, you might pass it to JS somehow so that JS call "notify()" after an interval. Another example to put task into a structure that might be triggered from a different future (this is how channels work). 

So the future here isn't good. You need not call `notify()` here as it will be called by sender after the task was registered by `receiver.poll()` .

> If it is indeed valid behavior, then we need to defer the reexecution by using setTimeout / requestAnimationFrame / ... so the runtime can make progress in the meantime, allowing the future to eventually resolve itself.

I'm not sure what you mean here. But to make it right you can do two things:

1. Add `requestAnimationFrame` in task.notify()
2. Patch ` stdweb::Once` to run executor every time after callback is called.

**Comment by Pauan** [comment] 2018-02-09 07:44
> @tailhook FuturesUnordered would behave the same. So yes, it's completely acceptable deadlock.

Great! That significantly simplifies our implementation.

> So the future here isn't good.

That's good to know!

> You need not call notify() here as it will be called by sender after the task was registered by receiver.poll()

Yes, it was never intended that somebody would actually write a Future like that, it is just for testing purposes to make sure we handle **all** edge cases correctly.

> I'm not sure what you mean here. [...] Add requestAnimationFrame in task.notify()

Yup, that's what we're already doing. Right now we use `setTimeout`, which yields to the JavaScript event loop. This allows the previously mentioned test Future to (eventually) complete.

However, using `setTimeout` is tricky and really complicates the implementation, so we would rather not use it. But if we remove `setTimeout` then the Future will cause a 100% CPU infinite loop deadlock.

So we just wanted to make sure that it's okay to remove `setTimeout` (and thus causing deadlock, but simplifying our implementation). And you've answered that question for us, thanks!

**Comment by alexcrichton** [comment] 2018-02-12 17:36
Thanks for the report! Are there still some lingering concerns here or did @tailhook cover everything though? (sorry got lost a bit in the comments here...)

**Comment by Pauan** [comment] 2018-02-12 17:58
@alexcrichton I think we got all our questions answered, thanks.

Though it would be nice if these edge cases were documented more thoroughly, such as:

* If a Future calls `task.notify()` multiple times within a certain time frame, it's okay for the Executor to only call `poll` once (rather than once per `task.notify()`)

* It's okay for the Executor to deadlock if the Future synchronously calls `task.notify()` inside of `poll`

* Futures aren't supposed to call `task.notify()` if they have not made any progress

That would help out people who want to make their own Executors.

**Comment by alexcrichton** [comment] 2018-02-12 18:55
@Pauan certainly! Our documentation for building your own executor is quite lacking right now :)

That being said the point about deadlock I don't think is quite right. If a future synchronously calls `task.notify()` inside of its own `poll` that's still expected to work (sort of like a yield)

**Comment by Pauan** [comment] 2018-02-12 19:20
@alexcrichton Absolutely, a "well-behaved" Future should be able to call `task.notify()` inside of `poll` without deadlocking, but that's not what I meant. I meant a Future like this:

```rust
struct MyFuture;

impl Future for MyFuture {
    type Item = ();
    type Error = ();

    fn poll(&mut self) -> futures::Poll<Self::Item, Self::Error> {
        let task = futures::task::current();

        task.notify();

        Ok(futures::Async::NotReady)
    }
}
```

With our Executor (and a couple other Executors I tested) this will cause a 100% CPU infinite loop deadlock, which I believe is the expected behavior (or at the very least the Executor is *allowed* to deadlock in that situation).

It's a bit hard to precisely specify when an Executor is allowed to deadlock vs when it shouldn't. The above case is obvious, but there's probably much more subtle situations which are harder to decide.

**Comment by alexcrichton** [comment] 2018-02-12 19:41
Ah yes indeed, I misunderstood! Sounds like you've got everything sorted out @Pauan.

@Pauan would you be up for opening an issue on the "doc deficiencies" of writing an executor?

**Comment by Pauan** [comment] 2018-02-12 20:07
@alexcrichton Done: https://github.com/rust-lang-nursery/futures-rs/issues/754

**Comment by alexcrichton** [comment] 2018-02-12 20:08
Thanks! In that case I'll close this in favor of that

**Closed by alexcrichton** 2018-02-12 20:08 UTC
