### ISSUE TITLE
async is not zero-cost

### ISSUE THREAD

**Issue by kpp** [rust-lang-nursery/futures-rs#1571] opened 2019-04-28 11:54 UTC
See my post https://www.reddit.com/r/rust/comments/bi9yzs/async_is_not_zerocost/.

Long story short, given the most simple function [future::ready](https://docs.rs/futures-async-combinators/0.2.0/futures_async_combinators/future/fn.ready.html) among all combinators:

```
pub async fn ready<T>(value: T) -> T {
    value
}
```

I benchmarked it against https://rust-lang-nursery.github.io/futures-api-docs/0.3.0-alpha.15/futures/future/fn.ready.html. with:

```
executor::block_on(async {
   for _ in 1..n {
       await!(ready(42));
   }
});
```

Conclusion:

futures-rs is **~1.85** faster than async version of `ready` without lto and **~1.20** times faster with lto.

I hope the compiler and futures-rs teams will dig into what's going on and why `async fn` slows down the code a little bit.

**Comment by lnicola** [comment] 2019-04-28 14:10
CC @cramertj, @stjepang since TLS came up in https://github.com/rust-lang/rust/pull/59119.

**Comment by kpp** [comment] 2019-04-28 14:25
> since TLS came up in rust-lang/rust#59119.

```diff
thread_local! {
-    static TLS_WAKER: Cell<Option<NonNull<Waker>>> = Cell::new(None);
+    static TLS_CX: Cell<Option<NonNull<Context<'static>>>> = Cell::new(None);
}
```

Wasn't TLS before?

**Comment by yoshuawuyts** [comment] 2019-04-29 14:39
> Congrats, @rust-lang-nursery and personally @alexcrichton , your futures' combinators are faster than async/await solution. 

@kpp maybe it's just me, but I feel you're coming off rather hostile here.

Even if you didn't intend to come off that way, the fact that it can be interpreted as such adds unnecessary tension to what is essentially a bug report.

I'm sure the futures team would be happy to help get at the bottom of any (perceived) performance regressions, as _everyone_ here wants async rust to be as good as possible. But that requires at the very least we maintain a base level of respect towards each other.

**Comment by kpp** [comment] 2019-04-29 14:42
> I feel you're coming off rather hostile here.

I am sorry, I did not want to hurt anyone. Shall I delete my article on reddit and file a bug somewhere?

**Comment by cramertj** [comment] 2019-04-29 17:01
One easy answer here is that the structure we generate for `futures::future::Ready<T>` is basically just `Option<T>`, which is pretty well optimized. By contrast, `async fn ready<T>(x: T) { x }` turns into sometihng like `struct ReadyGenerator<T> { state: i32, x: T }` where `x` is a maybe-invalid `T`. That, combined with the current use of TLS, makes it pretty unsurprising to me that there'd be a performance difference in this super-micro benchmark. TBH I'm surprised the difference isn't bigger. Without things like the optimizations @tmandry has been working on over in https://github.com/rust-lang/rust/issues/52924, I'd expect futures combinators (which are just about as optimized as it is possible to be) to continue being more performant than `async`/`await` generated code. These limitations aren't fundamental, though, and I'm looking forward to continued improvements here.

I'm going to close this issue, since it doesn't really represent any particular bug. The other bits of work I've mentioned above (generator representation, TLS) are already tracked in other issues.

**Closed by cramertj** 2019-04-29 17:01 UTC

**Comment by kpp** [comment] 2019-04-29 17:20
Thanks

**Comment by yoshuawuyts** [comment] 2019-04-29 20:14
> I am not a native English speaker, I did not mean to hurt anyone.

No worries, glad it was just a misunderstanding!

**Comment by Pauan** [comment] 2019-04-30 00:47
> @kpp I was told about this meaning in a private conversation. I am not a native English speaker, I did not mean to hurt anyone.

To be clear, the issue isn't with the word "congrats" (which is fine).

The issue is that it portrayed futures-rs as competing with async/await, which isn't correct: the futures-rs team works closely together with the Rust lang team, and people like @alexcrichton have done a lot of work on futures-rs *and* the Rust compiler.

So it's not really competing at all, there's a *lot* of overlap between futures-rs and Rust itself.
