### ISSUE TITLE
From trait on SharedError

### ISSUE THREAD

**Issue by nyarly** [rust-lang-nursery/futures-rs#660] opened 2017-11-24 19:24 UTC
Having shared() and clone()'d a future, I'm getting

```
src/destiny/mod.rs|83 col 32 error 277| the trait bound `futures::future::SharedError<errors::Error>: std::convert::From<errors::Error>` is not satisfied
||    |
|| 83 |       let dbpath = cache_path(&database_name_from_path(&urlpath)?)?;
||    |                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `std::convert::From<errors::Error>` is not implemented for `futures::future::SharedError<errors::Error>`
||    |
||    = note: required by `std::convert::From::from`
```

(I'm also using error-chain here)

It looks like I'm going to have to work around this by handing Results in my future creators, instead of leaning on IntoFuture being implemented for Result.

It would be handy if there were `impl std::convert::From<From<T>> on SharedError<T>` is that reasonable?

**Comment by nyarly** [comment] 2017-11-24 20:27
Alternatively, I wound up doing:
```
    .then(|res| match res {
      Ok(it) => Ok(*it),
      Err(err) => Err(*err),
    })
```
which I think'll do what I want. Does it make sense to have an `.unshare()` by analogy to `.flatten()`?

**Comment by nyarly** [comment] 2017-11-24 21:49
Ugh. Nevermind. I had to extract a very special purpose version of the above as `unshare_result` to get inference to work. I don't think it'd work elsewhere.

**Comment by alexcrichton** [comment] 2017-11-25 15:16
This seems liek a plausible impl to add, but I'd also imagine that there's not many contexts where you want to unify with a `SharedError`? Or maybe there are many?

**Comment by nyarly** [comment] 2017-11-25 23:28
My use case was like this: I had a longish sequence of AndThens, and I realized that I had a separate sequence I would need to join on that started from a point about midway along. So: I broke the sequence in the middle, added a `.shared()` to the end of the first half, and gave the second half a new name, starting from `first_half.clone()`

However, all my AndThens in the second half were built with the type assumptions of being in one sequence. Also key here is that I'm using chain-error (I've been advised to switch to the failure crate... next time.)  I can't `foreign_link` SharedError because a) it's private and b) it's not `Send` (iirc).

I was relying pretty heavily on Result being IntoFuture, so many of my steps were returning errors - I'm not sure how I could start producing SharedErrors in the latter part?

Hence, at the start of each of the shared consumer chains, I've added a call to my `unshare_result` function:
```
fn unshare_result<T,U: ::std::ops::Deref,E: ::std::ops::Deref>(res: ::std::result::Result<U, E>) -> Result<U::Target>
where U::Target: Sized + Clone,
      E::Target: Sized,
      Error: convert::From<E::Target>
{
  match res {
    Ok(it) => Ok((*it).clone()),
    Err(_) => bail!("just broken")
  }
}
```
(For my purposes U::Target could be String; I need to turbofish it in practice.)

All in all, this feels like a pretty awkward workaround, but I can't see the way forward. Probably there's a less-local maxima to chase?

**Comment by alexcrichton** [comment] 2017-11-29 15:14
Hm ok thanks for the explanation! I agree that I'm not entirely sure what the best way to model this would be. I'd imagine that async/await would help reduce the need for unified error types and such here in the first place, but I'm not sure how far we want to go on the ergonomics of each combinator in isolation (e.g. how souped up `SharedError` should be...

**Comment by sdleffler** [comment] 2018-02-23 23:05
Hi! I've run into a similar issue with `failure`, but coming from a slightly different direction. I've decided to drop a comment here rather than create a new issue because the problem is similar: `SharedError<E>` does not implement `Fail` for `E: Fail` which necessitates a `ResultExt::compat` or `Error::compat` or `Fail::compat` call in order to convert the error into a compatible representation which implements `Error` over `Fail`. This results in a very confusing and difficult to read error message which can basically be summarized as "SharedError doesn't implement Fail because SharedError does not implement Error because E does not implement Error". Which is true, since E is Fail, and Fail does not imply Error!

Anyhow, I'd like to request perhaps a `failure` feature, stuck behind a feature flag, which enables `Fail` impls for `SharedError` based on `E: Fail`.

**Comment by alexcrichton** [comment] 2018-02-26 15:40
@sdleffler I think with failure's soon bump to 1.0.0 we should definitely be able to do that! Since that's a separable feature from this, though, mind opening a new issue to track it?

**Comment by cramertj** [comment] 2019-11-01 00:00
`SharedError` no longer exists-- closing.

**Closed by cramertj** 2019-11-01 00:00 UTC
Labels: C-feature-request
